arreglando la creacion del plato
JohanaForero/microservicio_plazoleta pull request #7
Opened 2023-05-13 23:36 UTC by JohanaForero

https://trello.com/c/XTzP2QgW

2023-05-14 11:14 UTC, leforero4-ui requested changes

2023-05-14 17:02 UTC, JaiderMartinez commented on src/main/java/com/reto/plazoleta/application/dto/response/CreateDishResponseDto.java
>  public class CreateDishResponseDto {
No, estamos usando el Java 11

2023-05-15 07:31 UTC, leforero4-ui requested changes

2023-05-15 07:31 UTC, leforero4-ui commented on src/main/java/com/reto/plazoleta/application/dto/response/CreateDishResponseDto.java
>  public class CreateDishResponseDto {
Vi que actualizaron la versión de java en esta pr, podria ser viable ahora utilizar records

2023-05-16 19:28 UTC, JohanaForero commented on src/main/java/com/reto/plazoleta/application/dto/request/CreateDishRequestDto.java
>  public class CreateDishRequestDto {
si señor pero nos toco devolver ala version 11 de java por q al intentar java 17 nos botaba error todo

2023-05-16 19:28 UTC, JohanaForero commented on src/main/java/com/reto/plazoleta/application/dto/response/CreateDishResponseDto.java
>  public class CreateDishResponseDto {
no toco devolver a java 11
por q nos botaba error

2023-05-16 19:29 UTC, JohanaForero commented on src/main/java/com/reto/plazoleta/application/handler/IOwnerRestaurantService.java
> +    void saveDish(CreateDishRequestDto createDishRequestDto);
si al devolver el response soluciono el problema y ahora si devuelve lo que declare en el response

2023-05-16 19:29 UTC, JohanaForero commented on src/main/java/com/reto/plazoleta/application/mapper/requestmapper/IDishRequestMapper.java
>          unmappedTargetPolicy = ReportingPolicy.IGNORE,
si hay puse los mismos nombres y se soluciono

2023-05-16 19:31 UTC, JohanaForero commented on src/test/java/com/reto/plazoleta/domain/usecase/OwnerRestaurantUseCaseTest.java
>      @Test
en la s pruebas de integracion utilizammos @SpringBoot

2023-05-16 19:31 UTC, JohanaForero commented on src/test/java/com/reto/plazoleta/domain/usecase/OwnerRestaurantUseCaseTest.java
>      void mustSaveDish() {
solucionamos el nombre del metodo de la prueba aplicando la nomenclatura

2023-05-16 19:34 UTC, JohanaForero commented on src/main/java/com/reto/plazoleta/application/mapper/requestmapper/IDishRequestMapper.java
> +    @Mapping(target = "restaurantModel.idRestaurant", source = "createDishRequestDto.idRestaurant")
si eliminamos la anotacion ReportingPolicy.IGNORE y funciono

2023-05-16 19:34 UTC, JohanaForero commented on src/main/java/com/reto/plazoleta/domain/OrderUseCase.java
> +
si elimine esa clase por que de verdad pues esta clase no aporta nada ala pr

2023-05-16 19:35 UTC, JohanaForero commented on src/main/java/com/reto/plazoleta/domain/CustomerUseCase.java
> +public class CustomerUseCase {
igual la ilimine por que no aporta ala pr

2023-05-16 20:13 UTC, leforero4-ui commented on src/test/java/com/reto/plazoleta/domain/usecase/OwnerRestaurantUseCaseTest.java
>      void mustSaveDish() {
[5/4, 10:02 AM] Luis: Los nombres de las pruebas pueden seguir este formato:
test_[nombreDelMetodoAProbar]_with[entrada]_when[sistema]_ShouldReturn/ShouldThrow[deberíaResponderOFallar]
Ejemplos:
test_covertStringToMoney_withStringAsNumber_whenSystemDolar_ShouldReturMoneyWithDolar
test_covertStringToMoney_withStringAsNumber_whenSystemEuro_ShouldReturMoneyWithEuro
test_convertStringToMoney_withStringAsNotNumber_whenSystemEuro_ShouldThrowFormatException
[5/4, 10:03 AM] Luis: Los nombres son super largos y tienen varios signos de raya piso: _ 
pero por lo general es la convención

2023-05-17 09:50 UTC, leforero4-ui requested changes

2023-05-17 09:50 UTC, leforero4-ui commented on src/main/java/com/reto/plazoleta/application/handler/impl/OwnerRestaurantService.java
> +import com.reto.plazoleta.domain.model.DishModel;
ejecute tareas de limpieza en los archivos modificados en esta pr para evitar importes innecesarios, formateo de código, y demás, se debería poner como regla en los desarrollos, en intellij está el atajo Ctrl + Alt + L.

2023-05-17 09:50 UTC, leforero4-ui commented on src/main/java/com/reto/plazoleta/application/mapper/requestmapper/IDishRequestMapper.java
> +    DishModel toDishModel(CreateDishRequestDto createDishRequestDto);
idDish necesita ignorarse

2023-05-17 09:50 UTC, leforero4-ui commented on src/main/java/com/reto/plazoleta/application/mapper/requestmapper/IDishRequestMapper.java
> +@Mapper(componentModel = "spring")
también se puede declarar que usará el IOC de spring muy util para convertir el mapper en bean,  en el build.gradle de esa forma se puede evitar declarar cada vez que se cree un mapper
`compileJava {
    options.compilerArgs = [
            '-Amapstruct.defaultComponentModel=spring'
    ]
}`

2023-05-17 09:50 UTC, leforero4-ui commented on src/main/java/com/reto/plazoleta/domain/usecase/OwnerRestaurantUseCase.java
> +        RestaurantModel restaurantModel = restaurantPersistencePort.findByIdRestaurant(dishModel.getRestaurantModel().getIdRestaurant());
un test de integración podría ser: que pasa si no viene el idRestaurante

2023-05-17 09:50 UTC, leforero4-ui commented on src/main/java/com/reto/plazoleta/infraestructure/entrypoint/OwnerRestaurantController.java
>      @PostMapping(value = "/")
el path podría ser mas declarativo

2023-05-18 06:24 UTC, leforero4-ui commented on src/test/java/com/reto/plazoleta/domain/RestaurantUseCaseTest.java
>      private RestaurantUseCase restaurantUseCase;
use @InyectMocks

2023-05-18 06:33 UTC, leforero4-ui commented on src/test/java/com/reto/plazoleta/domain/usecase/OwnerRestaurantUseCaseTest.java
>          verify(dishPersistencePort).saveDish(any(DishModel.class));
aún se ve revuelto, por favor agregue comentario indicando que bloque es de Given-When-Then
ejemplo:
`void miTest() {
  // Given
  Restaurant restaurant = this.createRestaurantModel();
  Menu menu = this.createMenuModel();
  
  when(this.miService.getMenu()).then(restaurant .getMenuModel());

  // When
  Menu menuResponse = this.miUseCase.getMenu();

  // Then
  Assert.equals(menu , menuResponse);
}`

2023-05-19 08:52 UTC, leforero4-ui commented on src/test/java/com/reto/plazoleta/domain/OwnerRestaurantUseCaseTest.java
> +        verify(restaurantPersistencePort, times(1)).findByIdRestaurant(1L);
los verify es parte del bloque Then, porque son validaciones

2023-05-19 08:58 UTC, leforero4-ui requested changes

2023-05-19 08:58 UTC, leforero4-ui commented on src/test/java/com/reto/plazoleta/domain/OwnerRestaurantUseCaseTest.java
> +        RestaurantModel restaurantModel = new RestaurantModel(1L, "sal", "bellavista",
agreguele a todos los test los comentarios por bloque Given-When-Then

2023-05-19 08:58 UTC, leforero4-ui commented on src/test/java/com/reto/plazoleta/infraestructure/entrypoint/OwnerRestaurantControllerTest.java
> +        restaurantRepository.save(new RestaurantEntity(1L, "salado", "bellavista",
si va a guardar un restaurante en cada prueba también sería bueno que borrara la bd antes de cada prueba

2023-05-19 08:58 UTC, leforero4-ui commented on src/test/java/com/reto/plazoleta/domain/OwnerRestaurantUseCaseTest.java
> +    void test_saveDish_withRequestIdRestaurantNotExists_ShouldThrowInvalidDataException() {
agregue los comentarios por bloque de Given-When-Then en todos los test de esta pr

2023-05-19 20:39 UTC, JohanaForero commented on src/test/java/com/reto/plazoleta/domain/OwnerRestaurantUseCaseTest.java
> +        verify(restaurantPersistencePort, times(1)).findByIdRestaurant(1L);
si señor ya lo corregi

2023-05-19 21:14 UTC, JohanaForero commented on src/test/java/com/reto/plazoleta/domain/OwnerRestaurantUseCaseTest.java
> +package com.reto.plazoleta.domain;
si comapañero tiene la razon ya lo solucione

2023-05-19 21:18 UTC, JohanaForero commented on src/test/java/com/reto/plazoleta/infraestructure/entrypoint/OwnerRestaurantControllerTest.java
> +        restaurantRepository.save(new RestaurantEntity(1L, "salado", "bellavista",
si señor ya acomode esa parte

2023-05-19 21:19 UTC, JohanaForero commented on src/test/java/com/reto/plazoleta/infraestructure/entrypoint/OwnerRestaurantControllerTest.java
> +    private MockMvc mockMvc;
si señor ya lo aregle

2023-05-19 22:06 UTC, leforero4-ui requested changes

2023-05-19 22:06 UTC, leforero4-ui commented on src/test/java/com/reto/plazoleta/infraestructure/entrypoint/OwnerRestaurantControllerTest.java
> +        restaurantRepository.save(new RestaurantEntity(1L, "salado", "bellavista",
no veo el ajuste, y faltan mas pruebas

2023-05-19 22:06 UTC, leforero4-ui commented on src/test/java/com/reto/plazoleta/domain/usecase/OwnerRestaurantUseCaseTest.java
>      }
el assert va dentro del then y el llamado del método va dentro del when, si no es posible separarlo agreguele el comentario 
// When - Then

2023-05-20 08:57 UTC, leforero4-ui requested changes
aplique formateo de código en todos los archivos de esta pr
use CTRL + ALT + L en intellij

2023-05-20 08:57 UTC, leforero4-ui commented on build.gradle
> +
elimine estas dos líneas vacias

2023-05-20 09:31 UTC, leforero4-ui requested changes

2023-05-20 09:31 UTC, leforero4-ui commented on src/test/java/com/reto/plazoleta/infraestructure/entrypoint/OwnerRestaurantControllerTest.java
> +
faltan mas pruebas, y elimine las líneas vacias, por favor revise los archivos de su pr, elimine lineas vacias innecesarias y aplique el formateo de intellij

2023-05-21 03:59 UTC, JohanaForero commented on src/test/java/com/reto/plazoleta/domain/OwnerRestaurantUseCaseTest.java
> +        RestaurantModel restaurantModel = new RestaurantModel(1L, "sal", "bellavista",
si ya le agregue a todos los test los comentarios por bloque Given-When-Then

2023-05-21 03:59 UTC, JohanaForero commented on build.gradle
> +
si ya elimine las lineas vacias

2023-05-21 04:01 UTC, JohanaForero commented on src/test/java/com/reto/plazoleta/infraestructure/entrypoint/OwnerRestaurantControllerTest.java
> +
si ya realize las pruebas necesarias

2023-05-21 10:52 UTC, leforero4-ui requested changes

2023-05-21 10:52 UTC, leforero4-ui commented on src/test/java/com/reto/plazoleta/infraestructure/entrypoint/OwnerRestaurantControllerTest.java
> +
no veo la prueba de cuando el precio es 0 o valor negativo, por favor revise si hacen falta mas pruebas adicionales que cubran todos los casos y aseguren que no lleguen bgs a producción o bugs cuando se agreguen mas desarrollos de hus

2023-05-21 10:56 UTC, leforero4-ui requested changes

2023-05-21 10:56 UTC, leforero4-ui commented on src/test/java/com/reto/plazoleta/domain/usecase/OwnerRestaurantUseCaseTest.java
> +        //When
la línea vacia debía ir antes del comentario no después, por favor revisé esto mismo en los otros comentarios de las demás clases de esta pr

2023-05-21 18:10 UTC, JohanaForero commented on src/main/java/com/reto/plazoleta/domain/model/CategoryModel.java
>      public CategoryModel() {
si resuelto y no pudimos usar record por la version de java

2023-05-21 18:10 UTC, JohanaForero commented on src/test/java/com/reto/plazoleta/domain/usecase/OwnerRestaurantUseCaseTest.java
>      void mustSaveDish() {
ya aregle la nomenclatura de los nonmbres de los test

2023-05-21 18:11 UTC, JohanaForero commented on src/test/java/com/reto/plazoleta/domain/RestaurantUseCaseTest.java
>  class RestaurantUseCaseTest {
si ya resolvi los nombres de los test

2023-05-21 18:12 UTC, JohanaForero commented on src/test/java/com/reto/plazoleta/domain/RestaurantUseCaseTest.java
>      private RestaurantUseCase restaurantUseCase;
si ya lo usamos y aplique la nomenclatura

2023-05-21 18:29 UTC, JohanaForero commented on src/test/java/com/reto/plazoleta/domain/usecase/OwnerRestaurantUseCaseTest.java
> +        //When
ya la elimine

2023-05-21 18:29 UTC, JohanaForero commented on src/test/java/com/reto/plazoleta/domain/RestaurantUseCaseTest.java
>  class RestaurantUseCaseTest {
ya la use

2023-05-21 20:42 UTC, JohanaForero commented on src/main/java/com/reto/plazoleta/application/dto/response/CreateDishResponseDto.java
> +    private RestaurantModel nameRestaurant;
si ya se soluciono

2023-05-21 20:43 UTC, JohanaForero commented on src/main/java/com/reto/plazoleta/application/dto/response/CreateDishResponseDto.java
> +    private CategoryModel nameCategory;
si ya lo solucione

2023-05-22 02:51 UTC, leforero4-ui requested changes
Agregar evidencia de las pruebas en trello

2023-05-22 02:51 UTC, leforero4-ui commented on src/test/java/com/reto/plazoleta/domain/RestaurantUseCaseTest.java
>  class RestaurantUseCaseTest {
No se usó @InjectMock en esta clase,
La constante token debe ir en mayuscula y el orden es static final

2023-05-22 02:51 UTC, leforero4-ui commented on src/test/java/com/reto/plazoleta/domain/RestaurantUseCaseTest.java
>      private RestaurantUseCase restaurantUseCase;
todavía no veo que lo usen en está clase,
los nombres no están de acuerdo a la nomenclatura.
además le falta agregar los comentarios del bloque Given-When-Then

2023-05-22 02:51 UTC, leforero4-ui commented on src/test/java/com/reto/plazoleta/domain/RestaurantUseCaseTest.java
>  class RestaurantUseCaseTest {
los nombres no están de acuerdo a la nomenclatura.

2023-05-23 13:41 UTC, JohanaForero commented on src/test/java/com/reto/plazoleta/domain/RestaurantUseCaseTest.java
>  class RestaurantUseCaseTest {
si señor eso ya se corrigio es que eso era de la pr de mi compañero pero ya lo corrigio el y le dio merge y yo baje los cambios

2023-05-23 13:43 UTC, JohanaForero commented on src/test/java/com/reto/plazoleta/domain/RestaurantUseCaseTest.java
>  class RestaurantUseCaseTest {
si señor ya se corrrigio igual que el anterior es de mi compañero ya el corrigio y dio merge y yo baje los cambios eso ya se resolvio

2023-05-23 19:30 UTC, leforero4-ui approved these changes

2023-05-23 23:51 UTC, merged